[package]
name = "reactor-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reactor-identity = { path = "../reactor-identity" }
reactor-auth = { path = "../reactor-auth" }
reactor-storage = { path = "../reactor-storage" }
reactor-functions = { path = "../reactor-functions" }
reactor-sites = { path = "../reactor-sites" }
reactor-email = { path = "../reactor-email" }
reactor-core = { path = "../reactor-core" }
reactor-ext-queue = { path = "../reactor-ext-queue" }
tokio = { workspace = true }
axum = { workspace = true, features = ["macros"] }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
lambda_http = { workspace = true }
aws-config = { workspace = true }
aws-sdk-lambda = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
aes-gcm = { workspace = true }
base64 = { workspace = true }
jsonwebtoken = { workspace = true }
toml = "0.8"
totp-rs = { version = "5", features = ["gen_secret", "otpauth"] }
url = "2"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
pg_query = "6.2"
webauthn-rs = { version = "0.5", features = ["danger-allow-state-serialisation"] }

[dev-dependencies]
p256 = { version = "0.13", features = ["pem"] }
tokio = { workspace = true }
tower = { workspace = true }
http-body-util = { workspace = true }
